[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.5.1"
pest_derive = "2.5.1"
pixels = "0.10.0"
winit = "0.27.5"
winit_input_helper = "0.13.0"
serde = { version = "1.0.150", features = ["serde_derive"] }
serde_json = "1.0.89"
once_cell = "1.16.0"
regex = "1.7.0"